{% set version = "2.0-0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-geomapdata
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/geomapdata_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/geomapdata/geomapdata_{{ version }}.tar.gz
  sha256: 443db35b673a0883baae28064210d1058bbba7cd49db036be33386e87d870757

build:
  merge_build_host: true  # [win]
  number: 2
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('geomapdata')"           # [not win]
    - "\"%R%\" -e \"library('geomapdata')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=geomapdata
  license: GPL-2.0-or-later
  summary: Set of data for use in package GEOmap.  Includes world map, USA map, Coso map, Japan Map, ETOPO5
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: geomapdata
# Type: Package
# Title: Data for topographic and Geologic Mapping
# Version: 1.0-4
# Date: 2007-10-23
# Suggests: GEOmap
# Author: Jonathan M. Lees
# Maintainer: Jonathan M. Lees<jonathan.lees@unc.edu>
# Depends: R (>= 2.10)
# Description: Set of data for use in package GEOmap.  Includes world map, USA map, Coso map, Japan Map, ETOPO5
# License: GPL
# Packaged: 2012-10-29 08:58:49 UTC; ripley
# Repository: CRAN
# Date/Publication: 2012-10-29 08:58:53
